# Generated by Django 4.2 on 2024-07-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_vote'),
        ('products', '0010_alter_product_price'),
    ]

    operations = [
    ]
