# Generated by Django 4.2.14 on 2024-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_reportedreview_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportedreview',
            options={'verbose_name_plural': 'Reported Reviews'},
        ),
        migrations.RenameField(
            model_name='reportedreview',
            old_name='reported_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='reportedreview',
            name='user',
        ),
        migrations.AddField(
            model_name='reportedreview',
            name='reason',
            field=models.CharField(default='', max_length=255),
        ),
    ]
