# Generated by Django 5.0.6 on 2024-06-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
